version: "3"

services:
    db:
        image: mysql
        ports:
            - 3309:3306
        volumes:
            - reddit-analysis:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        build:
            dockerfile: App.Dockerfile
            context: .
        environment:
            MYSQL_ROOT_PASSOWRD: root
        volumes:
            - ./:/app

volumes:
    reddit-analysis:
        external: false