version: "3"

services:
    db:
        image: mysql
        ports:
            - 3309:3306
        volumes:
            - reddit-analysis:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
    app:
        build:
            dockerfile: App.Dockerfile
            context: .
        environment:
            MYSQL_ROOT_PASSOWRD: root
        volumes:
            - ./Code:/app/Code
    web:
        build:
            dockerfile: Web.Dockerfile
            context: .
        ports:
            - "86:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./Web:/var/www/html

volumes:
    reddit-analysis:
        external: false